version: '3.9'

services:
  

  server:
    env_file: .env
    build:
      context: .
    container_name: go04
    restart: unless-stopped
    networks:
      - default
    expose:
      - "${API_PORT}"

  proxy:
    image: nginx:alpine
    container_name: nx04
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    networks:
      - default

volumes:
  local_postgres_data: {}

networks:
  default:
    driver: bridge